version: '2'
services:
    blackhole-app:
        image: blackhole
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://blackhole-mysql:3306/blackhole?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    blackhole-mysql:
        extends:
            file: mysql.yml
            service: blackhole-mysql
